openapi: '3.0.0'
# modularized based off: https://github.com/OAI/OpenAPI-Specification/issues/1961
info:
  version: 1.0.0
  title: Brain Drip
  description: The official v2 Brain Drip API
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /v1
paths:
  /users:
    $ref: './users/users.yml#/users'
  /users/{id}:
    $ref: './users/userById.yml#/userById'
  /learning-path:
    $ref: './learningpath/learningpath.yml#/learningPath'
  /learning-path/id/{id}:
    $ref: './learningpath/learningpathbyid.yml#/learningPathById'
  /learning-path/search:
    $ref: './learningpath/learningpathbyparams.yml#/learningPathByParams'
  /learning-path/search/{searchString}:
    $ref: './learningpath/learningpathbysearch.yml#/learningPathBySearch'
  /learning-path/resource:
    $ref: './learningpathresource/learningpathresource.yml#/learningPathResource'
  /sessions:
    $ref: './sessions/sessions.yml#/sessions'
  /auth/google:
    $ref: './auth/google.yml#/google'
  /auth/facebook:
    $ref: './auth/facebook.yml#/facebook'
  /auth/google/callback:
    $ref: './auth/googlecallback.yml#/googleCallback'
  /auth/facebook/callback:
    $ref: './auth/facebookcallback.yml#/facebookCallback'

components:
  schemas:
    User:
      required:
        - id
        - email
        - password
      properties:
        id:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
        # type:
        # 	$ref: '#/components/schemas/PetType'

    PetType:
      type: string
      enum:
        - dog
        - cat

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key