version: "3"
services:
    api-gateway:
        build: "./api-gateway"
        depends_on:
            - braindrip-backend
<<<<<<< HEAD
        environment:
            - BRAINDRIP_BACKEND_URI=http://braindrip-backend:7101/v1
=======
>>>>>>> 461ae08e90c0639bf52d9c202d1f2a55301920af
        ports:
            - 7000:7000
        volumes:
            - ./api-gateway:/opt/app

    braindrip-backend:
        build: "./braindrip-backend"
        depends_on:
            - braindrip-backend-db
        environment:
            - DB_URI=mysql://root:password@braindrip-backend-db/db?charset=UTF8
        ports:
            - 7101:7101
        volumes:
            - ./braindrip-backend:/opt/app
    
    braindrip-backend-db:
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
        ports:
            - 0.0.0.0:7201:3306